const MASTER_DATA_TAGS = [
  'Technology',
  'Science',
  'Programming',
  'Web Development',
  'Mobile Development',
  'AI',
  'Machine Learning',
  'Data Science',
  'Software',
  'Hardware',
  'Cybersecurity',
  'Cloud Computing',
  'DevOps',
  'Networking',
  'Gaming',
  'Entertainment',
  'Movies',
  'Music',
  'Books',
  'Art',
  'Design',
  'Photography',
  'Fashion',
  'Travel',
  'Food',
  'Cooking',
  'Health',
  'Fitness',
  'Wellness',
  'Sports',
  'Education',
  'Learning',
  'Business',
  'Finance',
  'Investing',
  'Marketing',
  'Sales',
  'Entrepreneurship',
  'Startups',
  'E-commerce',
  'Retail',
  'Logistics',
  'Management',
  'Leadership',
  'Productivity',
  'Self-Improvement',
  'Personal Development',
  'Psychology',
  'Philosophy',
  'History',
  'Politics',
  'Economics',
  'Sociology',
  'Environment',
  'Sustainability',
  'Climate Change',
  'Nature',
  'Animals',
  'Pets',
  'Home Improvement',
  'DIY',
  'Gardening',
  'Crafting',
  'Hobbies',
  'Lifestyle',
  'News',
  'Current Events',
  'Society',
  'Culture',
  'Family',
  'Relationships',
  'Parenting',
  'Spirituality',
  'Religion',
  'Volunteering',
  'Charity',
  'Community',
  'Non-profit',
  'Research',
  'Academia',
  'Writing',
  'Blogging',
  'Podcasting',
  'Video Production',
  'Animation',
  'UX/UI',
  'Product Management',
  'Quality Assurance',
  'Human Resources',
  'Legal',
  'Healthcare',
  'Biotech',
  'Renewable Energy',
  'Space',
  'Astronomy',
  'Robotics',
  'IoT (Internet of Things)',
  'Big Data',
  'Virtual Reality',
  'Augmented Reality',
  'Architecture',
  'Interior Design',
  'Literature',
  'Poetry',
  'Journalism',
  'Comedy',
  'Theater',
  'Dance',
  'Opera',
  'Classical Music',
  'Jazz',
  'Rock',
  'Pop',
  'Hip Hop',
  'Electronic Music',
  'World Music',
  'Fine Art',
  'Sculpture',
  'Drawing',
  'Painting',
  'Digital Art',
  'Street Art',
  'Graphic Design',
  'Web Design',
  'Game Design',
  'Industrial Design',
  'Urban Planning',
  'Real Estate',
  'Construction',
  'Manufacturing',
  'Engineering',
  'Aerospace',
  'Automotive',
  'Robotics',
  'Nanotechnology',
  'Genetics',
  'Biology',
  'Chemistry',
  'Physics',
  'Mathematics',
  'Statistics',
  'Astronomy',
  'Geology',
  'Oceanography',
  'Meteorology',
  'Environmental Science',
  'Zoology',
  'Botany',
  'Paleontology',
  'Archeology',
  'Anthropology',
  'Linguistics',
  'Mythology',
  'Folklore',
  'Spirituality',
  'Meditation',
  'Yoga',
  'Mindfulness',
  'Therapy',
  'Counseling',
  'Mental Health',
  'Nutrition',
  'Diet',
  'Exercise',
  'Sports Science',
  'Team Sports',
  'Individual Sports',
  'Outdoor Activities',
  'Adventure',
  'Camping',
  'Hiking',
  'Fishing',
  'Hunting',
  'Boating',
  'Skiing',
  'Snowboarding',
  'Surfing',
  'Diving',
  'Gardening',
  'Horticulture',
  'Agriculture',
  'Farming',
  'Cooking Recipes',
  'Baking',
  'Desserts',
  'Beverages',
  'Wine',
  'Beer',
  'Coffee',
  'Tea',
  'Travel Guides',
  'Backpacking',
  'Luxury Travel',
  'Budget Travel',
  'Road Trips',
  'Cruises',
  'Beaches',
  'Mountains',
  'Cities',
  'Rural Life',
  'Frugal Living',
  'Minimalism',
  'Organization',
  'Decluttering',
  'Parenting Tips',
  'Child Development',
  'Teenagers',
  'Elder Care',
  'Pet Care',
  'Dog Training',
  'Cat Behavior',
  'Aquariums',
  'Reptiles',
  'Birds',
  'Wildlife',
  'Conservation',
  'Animal Welfare',
  'Human Rights',
  'Social Justice',
  'Equality',
  'Diversity',
  'Inclusion',
  'Refugees',
  'Poverty',
  'Homelessness',
  'Disability Rights',
  'Veterans',
  'Seniors',
  'Youth Development',
  'Education Reform',
  'Online Learning',
  'Homeschooling',
  'Vocational Training',
  'Skill Development',
  'Public Speaking',
  'Negotiation',
  'Critical Thinking',
  'Problem Solving',
  'Creativity',
  'Innovation',
  'Teamwork',
  'Collaboration',
  'Communication',
  'Presentation Skills',
];

export const TAGS = MASTER_DATA_TAGS.sort();
